# This file contains values from Cookiecutter

default_context:
  project_name: "pythoncms"
  project_description: "Python CMS is an easy-to-use, instant-operations CMS"
  organization: "shopyo"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "shopyo"
  email: "arj.python@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
